// autogenerated by msggen.c from msg/packet.msg

// message definition:
// u16 preamble
// u32 sno
// u32 secs
// u32 usecs
// u32 datalen
// u16 datatype
// u8 checksum
// str data

#ifndef SPROCKETS_AUTOGEN_MESSAGE_packet_H
#define SPROCKETS_AUTOGEN_MESSAGE_packet_H

#include <stdint.h>
#include <stddef.h>

#pragma pack(push, 1)
typedef struct
{
    uint16_t preamble;
    uint32_t sno;
    uint32_t secs;
    uint32_t usecs;
    uint32_t datalen;
    uint16_t datatype;
    uint8_t checksum;
    char data[128];
}
packet_t;
#pragma pack(pop)

void print_packet(const packet_t *m);

packet_t new_packet();

void serialize_packet(const packet_t *m, uint8_t *dst);

int deserialize_packet(packet_t *dst, const uint8_t *buffer, size_t len);

#endif // SPROCKETS_AUTOGEN_MESSAGE_packet_H

