// autogenerated by msggen.c from msg/timestamp.msg

// message definition:
// u32 secs
// u32 usecs

#include <msg/timestamp.h>
#include <stdio.h>

void print_timestamp(const timestamp_t *m)
{
    printf("timestamp_t ");
    printf("secs=%d ", m->secs);
    printf("usecs=%d ", m->usecs);
    printf("\n");
}
