// autogenerated by msggen.c from msg/vec3.msg

// message definition:
// f32 x
// f32 y
// f32 z

#include <msg/vec3.h>
#include <stdio.h>

void print_vec3(const vec3_t *m)
{
    printf("vec3_t ");
    printf("x=%lf ", (double) m->x);
    printf("y=%lf ", (double) m->y);
    printf("z=%lf ", (double) m->z);
    printf("\n");
}
