// autogenerated by msggen.c from msg/vec3.msg

// message definition:
// f32 x
// f32 y
// f32 z

#include <msg/vec3.h>
#include <stdio.h>
#include <string.h>

void print_vec3(const vec3_t *m)
{
    printf("vec3_t ");
    printf("x=%lf ", (double) m->x);
    printf("y=%lf ", (double) m->y);
    printf("z=%lf ", (double) m->z);
    printf("\n");
}

vec3_t new_vec3()
{
    vec3_t ret;
    memset(&ret, 0, sizeof(ret));
    return ret;
}

void serialize_vec3(const vec3_t *m, uint8_t *dst)
{
    memcpy(dst, m, sizeof(vec3_t));
}

int deserialize_vec3(vec3_t *dst, const uint8_t *buffer, size_t len)
{
    if (len != sizeof(vec3_t)) { return -1; }
    memcpy(dst, buffer, len);
    return 0;
}

